apiVersion: v1
kind: Pod
metadata:
  name: devops-fastapi
  namespace: fastapi
  labels:
    app: fastapi
spec:
  containers:
  - image: devops/fastapi:latest
    command:
      - /bin/sh
      - "-c"
      - "uvicorn main:app --host 0.0.0.0 --port 8080 --workers 4"
    imagePullPolicy: Never
    name: alpine
  restartPolicy: Always
