apiVersion: v1
kind: Service
metadata:  
  name: fastapi-service
  namespace: fastapi
spec:
  selector:    
    app: fastapi
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
