apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: kube-system
spec:
  version: 8.4.3
  count: 1
  elasticsearchRef:
    name: quickstart

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/secure-backend: "true"
spec:
  tls:
  - hosts:
    - kibana.local  
  ingressClassName: nginx
  rules:
    - host: kibana.local
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: quickstart-kb-http
              port:
                number: 5601 

