apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helloworld-task
  namespace: tekton-tasks
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World"
